included:
  - Sources
  - Tests
excluded:
  - Tests/ToyboxKit/fixtures
disabled_rules:
  - type_name
  - nesting
  - line_length
  - force_try
  - cyclomatic_complexity
identifier_name:
  excluded: m # It's used to parse commandant options
