env:
  global:
  - LC_CTYPE=en_US.UTF-8
cache: carthage
os: osx
language: objective
osx_image: xcode9
matrix:
  include: 
  - install:
    - carthage update --platform mac
    script:
    - swiftlint
    - set -o pipefail && xcodebuild test -project Toybox.xcodeproj -scheme ToyboxKitTests -destination 'platform=macOS' | xcpretty -c 
    - set -o pipefail && xcodebuild build -project Toybox.xcodeproj -scheme toybox -destination 'platform=macOS' | xcpretty -c 
  - script:
    - swift build
    - swift run
