env:
  global:
  - LC_CTYPE=en_US.UTF-8
os: osx
language: objective-c
matrix:
  include:
    - osx_image: xcode10.2
      script:
        - swiftlint --strict
        - swift build
        - swift test
    - osx_image: xcode11
      script:
        - xcodebuild -list -workspace .swiftpm/xcode/package.xcworkspace
        - xcodebuild test -workspace .swiftpm/xcode/package.xcworkspace -scheme ToyboxKit
