env:
  global:
  - LC_CTYPE=en_US.UTF-8
before_install:
  - brew install swiftlint
install:
  - carthage update --platform mac
matrix:
  include:
  - os: osx
    language: objective-c
    osx_image: xcode8
    script:
    - swiftlint
    - set -o pipefail && xcodebuild test -project Toybox.xcodeproj -scheme ToyboxKitTests -destination 'platform=macOS' | xcpretty -c 
    - set -o pipefail && xcodebuild build -project Toybox.xcodeproj -scheme toybox -destination 'platform=macOS' | xcpretty -c 
